{TEMPLATE_NAMESPACE}:
    robot:
        lfd_hri_gui:
            ros__parameters:
                namespace: '/{TEMPLATE_NAMESPACE}'
                default_frame: '{TEMPLATE_PREFIX}yumi_base_link'
                frames: ['banana', 'bowl']
                ee_frame: '{TEMPLATE_PREFIX}yumi_task_tool'
                base_frame: '{TEMPLATE_PREFIX}yumi_base_link'
                bt_tick_freq: 0.4
                has_robot: True
                use_hri: True